## Data Mining for Networks

Yana RAGOZINA - Thomas PAUL

SI5 IAID FISA

In [2]:
import numpy as np

### Exercise 1

#### 1. Random walk kernel value of graphs

 1. Graphs G and G'

The first step is to compute the direct product graph of G and G'.

Then, with the direct product graph, we can compute the adjacency matrix.

This part has been done by hand, if the images are not visible in this cell, they can be located in the folder of this assignment.

Here is the adjacency matrix of the direct product graph G x G' computed by hand :

In [9]:
A = np.array([
     [0,0,0,0,0,1,1,1,0,1,1,1,0,1,1,1],
     [0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0],
     [0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0],
     [0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0],
     [0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

A.shape

(16, 16)

Now that we have the adjacency matrix, we need to compute for each k, the adjacency matrix to the power of k. 

k being the lengths of the walks. In our case we have k = 0, 1, 2, 3, 4.

In [11]:
A_0 = np.eye(A.shape[0])
A_1 = A
A_2 = np.linalg.matrix_power(A, 2)
A_3 = np.linalg.matrix_power(A, 3)
A_4 = np.linalg.matrix_power(A, 4)

A_3

array([[ 0,  0,  0,  0,  3, 12,  9,  9,  3, 12,  9,  9,  3, 12,  9,  9],
       [ 0,  0,  0,  0, 10,  9,  3,  3, 10,  9,  3,  3,  6,  9,  3,  3],
       [ 0,  0,  0,  0,  6,  2,  0,  0,  6,  2,  0,  0,  2,  2,  0,  0],
       [ 0,  0,  0,  0,  6,  2,  0,  0,  6,  2,  0,  0,  2,  2,  0,  0],
       [ 3, 10,  6,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [12,  9,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3, 10,  6,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [12,  9,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  6,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [12,  9,  2,  2,  0,  0,  0,  0,  0,  0,  0,

The following section does the sum of each previous matrix (like the formula) :

In [13]:
M = A_0 + A_1 + A_2 + A_3 + A_4

M

array([[100.,  48.,   6.,   6.,   3.,  13.,  10.,  10.,   3.,  13.,  10.,
         10.,   3.,  13.,  10.,  10.],
       [ 48.,  60.,  22.,  22.,  11.,  10.,   3.,   3.,  11.,  10.,   3.,
          3.,   7.,  10.,   3.,   3.],
       [  6.,  22.,  15.,  14.,   7.,   2.,   0.,   0.,   7.,   2.,   0.,
          0.,   2.,   2.,   0.,   0.],
       [  6.,  22.,  14.,  15.,   7.,   2.,   0.,   0.,   7.,   2.,   0.,
          0.,   2.,   2.,   0.,   0.],
       [  3.,  11.,   7.,   7.,  26.,  14.,   3.,   3.,  25.,  14.,   3.,
          3.,  11.,  14.,   3.,   3.],
       [ 13.,  10.,   2.,   2.,  14.,  24.,  13.,  13.,  14.,  23.,  13.,
         13.,  10.,  23.,  13.,  13.],
       [ 10.,   3.,   0.,   0.,   3.,  13.,  11.,  10.,   3.,  13.,  10.,
         10.,   3.,  13.,  10.,  10.],
       [ 10.,   3.,   0.,   0.,   3.,  13.,  10.,  11.,   3.,  13.,  10.,
         10.,   3.,  13.,  10.,  10.],
       [  3.,  11.,   7.,   7.,  25.,  14.,   3.,   3.,  26.,  14.,   3.,
          3.,  11.,  1

Finally, we do the sum of each value of the matrix (like the formula):

In [14]:
RWK = np.sum(M)

RWK

2418.0

 2. Graphs G' and G''

The first step is to compute the direct product graph of G' and G'' :

![alternative text](./DPG_G'xG''.jpg)

Then, with the direct product graph, we can compute the adjacency matrix :

![alternative text](./Ax_G'xG''.jpg)

This part has been done by hand, if the images are not visible in this cell, they can be located in the folder of this assignment.

Here is the adjacency matrix of the direct product graph G x G' computed by hand :

In [4]:
A = np.array([
     [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0],
     [0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0],
     [0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
     [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]])

A.shape

(16, 16)

Now that we have the adjacency matrix, we need to compute for each k, the adjacency matrix to the power of k. 

k being the lengths of the walks. In our case we have k = 0, 1, 2, 3, 4.

In [5]:
A_0 = np.eye(A.shape[0])
A_1 = A
A_2 = np.linalg.matrix_power(A, 2)
A_3 = np.linalg.matrix_power(A, 3)
A_4 = np.linalg.matrix_power(A, 4)

A_3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

The following section does the sum of each previous matrix (like the formula) :

In [6]:
M = A_0 + A_1 + A_2 + A_3 + A_4

M

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 2., 4., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 3., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 3., 6., 3., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 4., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 3., 6., 3., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 4., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 3., 6., 3., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 1., 4., 1., 1., 0., 0., 0.,

Finally, we do the sum of each value of the matrix (like the formula): 

In [7]:
RWK = np.sum(M)

RWK

138.0

To avoid to much code duplication, below is a random walk kernel value function :

In [ ]:
def random_walk_kernel_value(A):
    A_0 = np.eye(A.shape[0])
    A_1 = A
    A_2 = np.linalg.matrix_power(A, 2)
    A_3 = np.linalg.matrix_power(A, 3)
    A_4 = np.linalg.matrix_power(A, 4)

    M = A_0 + A_1 + A_2 + A_3 + A_4

    return np.sum(M)